
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class LoginCheck extends javax.swing.JFrame {

    /**
     * Creates new form LoginCheck
     */
    public LoginCheck() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Username = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        tbnLogin = new javax.swing.JButton();
        btnLamMoiCheck = new javax.swing.JButton();
        btnThoatCheck = new javax.swing.JButton();
        backgrouplogin = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ĐĂNG NHẬP");
        setMinimumSize(new java.awt.Dimension(470, 411));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Username.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Username.setText("Username");
        getContentPane().add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        Password.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Password.setText("Password");
        getContentPane().add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        txtUsername.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 110, 30));

        txtPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 110, 30));

        tbnLogin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tbnLogin.setText("Đăng Nhập");
        tbnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(tbnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        btnLamMoiCheck.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLamMoiCheck.setText("Làm Mới");
        btnLamMoiCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiCheckActionPerformed(evt);
            }
        });
        getContentPane().add(btnLamMoiCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, -1, -1));

        btnThoatCheck.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnThoatCheck.setText("Thoát");
        btnThoatCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatCheckActionPerformed(evt);
            }
        });
        getContentPane().add(btnThoatCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, -1, -1));

        backgrouplogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/amy-shamblen-1061809-unsplash.jpg"))); // NOI18N
        getContentPane().add(backgrouplogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 470, 160));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/iconLogin.png"))); // NOI18N
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 110, 80));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tbnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbnLoginActionPerformed
         try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
		            String url="jdbc:sqlserver://ADMIN\\SQLEXPRESS;databaseName=CuoiKy;user=tuyen;password=1234";
		            Connection con=DriverManager.getConnection(url);
                             String sql="Select * from Taikhoan where Username=? and Password=?";
                             
            PreparedStatement pst=con.prepareStatement(sql);
            pst.setString(1, txtUsername.getText());
            pst.setString(2, txtPassword.getText());
            ResultSet rs=pst.executeQuery();
            if(rs.next())
            {
              //  JOptionPane.showMessageDialog(null,"đăng nhập thành công");
              // JOptionPane.showMessageDialog(null,"Xin Chào ");
                JOptionPane.showMessageDialog(null,"Xin Chào Bạn :  "+rs.getString("UserName"));
                
                System.out.println("Ket Noi SQL Thanh Cong");
               // this.dispose();
               // Table.main(null);
             this.setVisible(false);
                //new Table().setVisible(true);
                Main.main(null);
                
            }
            else{
                JOptionPane.showMessageDialog(null, "Username Hoặc Password Không Đúng ");
               
            }
            con.close();
        } catch (Exception e) {
             //JOptionPane.showMessageDialog(null, ex.toString());
        }
     
    }//GEN-LAST:event_tbnLoginActionPerformed

    private void btnLamMoiCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiCheckActionPerformed
        txtUsername.setText("");
        txtPassword.setText("");
    }//GEN-LAST:event_btnLamMoiCheckActionPerformed

    private void btnThoatCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatCheckActionPerformed
       this.dispose();
    }//GEN-LAST:event_btnThoatCheckActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginCheck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginCheck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginCheck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginCheck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginCheck().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Password;
    private javax.swing.JLabel Username;
    private javax.swing.JLabel backgrouplogin;
    private javax.swing.JButton btnLamMoiCheck;
    private javax.swing.JButton btnThoatCheck;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton tbnLogin;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
